### ISSUE TITLE
configure module

### ISSUE THREAD

**Issue by fmontaldo** [edestecd/puppet-clamav#36]
Hi Chris,

Sorry if bother with this question but I ma news in the puppet world. I want to know the way to configure the module in red hat satellite or foreman. I don't understand the way in which I have to configure the module to work. How is the process to add the parameters you mention in the module?

**Comment by ubellavance** [comment]
I don't know Satellite at all. I've used Foreman and it was not different than having a puppet-only server. Do you already have a Satellite server? A Foreman server?

To use this module, you must have a puppet server, and execute the command `puppet module install edestecd-clamav`, then you must add directives to your manifests.  Have you started using puppet at all?

**Comment by fmontaldo** [comment]
I got the assigment to do it but I really don't know the way to configire
the module. Do you have a guide to configire the manisfest. I can document
it and pass it to the group.

Thanks in advance

**Comment by ubellavance** [comment]
https://github.com/edestecd/puppet-clamav/blob/master/README.md is the module's documentation.

**Comment by edestecd** [comment]
From what I understand satellite is just a supported and bundled foreman/katello with some other tools.

You need to first get the module installed on your puppet server with the command mentioned above, or use something like librarian-puppet or R10k (highly recommended in mature environments)

Once the module is installed you can use many ways to include it on a server and configure the parameters. Foreman offers one way to do this in the web ui: https://www.digitalocean.com/community/tutorials/how-to-use-foreman-to-manage-puppet-nodes-on-ubuntu-14-04#add-ntp-module-to-foreman

We started out using that with Foreman, but we now prefer to do this in code rather than use the web UI.
I highly recommend moving to a roles and profiles pattern and classifying with nodes or hiera eventually, as you mature:
https://docs.puppet.com/pe/2017.2/r_n_p_full_example.html
https://docs.puppet.com/pe/2017.2/r_n_p_intro.html

**Comment by edestecd** [comment]
@fmotnaldo, Hopefully we have answered your question. If not feel free to reopen this or another issue.
