### ISSUE TITLE
Changing uid while process is clamav-daemon is already running

### ISSUE THREAD

**Issue by wojciej** [edestecd/puppet-clamav#6]
Hi,
I have notice the following issue while applying the puppet-clamav

Error: Could not set uid on user[clamav]: Execution of '/usr/sbin/usermod -u 496 clamav' returned 8: usermod: user clamav is currently used by process 13666

Error: /Stage[main]/Clamav::User/User[clamav]/uid: change from 114 to 496 failed: Could not set uid on user[clamav]: Execution of '/usr/sbin/usermod -u 496 clamav' returned 8: usermod: user clamav is currently used by process 13666

Debug: Class[Clamav::User]: The container Stage[main] will propagate my refresh event
Notice: /Stage[main]/Clamav/Package[clamav]: Dependency User[clamav] has failures: true
Warning: /Stage[main]/Clamav/Package[clamav]: Skipping because of failed dependencies

From my perspective it looks like puppet firstly start the daemon and then tries to change privileges on the user.
I have workaround this by not installing clamav::clamd class  ( cause I do not need it anyway)

version: OS
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

Version puppet:
Version: 3.4.3-1ubuntu1

However I just wanted you to know.
Thanks for a good job.

Regards
Jaroslaw Wojciechowski

**Comment by edestecd** [comment]
That is interesting.  I have seen that issue, but only after running puppet first with only:

``` puppet
class { 'clamav':
  manage_clamd => true,
}
```

Then running puppet a second time after adding:

``` puppet
class { 'clamav':
  manage_user  => true,
  manage_clamd => true,
}
```

Is it possible you did this?  I am not really sure how to make this work better, since we don't know you want to manage the user in the first run.  I think it's just best to know this going forward on new hosts.
You can fix this on existing hosts you ran it on by stopping the clamd service and allowing puppet to run again.  I could add the options to the module so you can make puppet ensure the service is stopped for one run also, if you want this...

`Class['clamav::clamd']` depends on `Class['clamav::user']`, so if you have this on the first run:

``` puppet
class { 'clamav':
  manage_user  => true,
  manage_clamd => true,
}
```

the user class should run first and you will avoid this problem.  If this is not the case and you have both turned on in the first run, please let me know, so I can investigate further.

**Comment by wojciej** [comment]
Thanks for such a fast replay.
So I got that issue when I have all 3 params set to false in clamav::params class

  #### init vars ####
  $manage_user      = false
  $manage_clamd     = false
  $manage_freshclam = false

When I set one of them to true I got errors that class has already been declared and cant be redeclared 

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Class[Clamav::Clamd] is already declared; cannot redeclare at /etc/puppet/environments/production/modules/clamav/manifests/init.pp:78 on node ...l
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Am I missing something here ? Or I configure it in the wrong place

**Comment by edestecd** [comment]
Can you paste in the code you are using to configure the clamav module?
It sounds like you may be declaring both

``` puppet
class { 'clamav':
}
# and
class {'clamav::clamd':
}
```

Usually you should only be using the main init class:

``` puppet
class { 'clamav':
  manage_clamd => true,
}
```

It will declare the other classes for you depending on the options you use.
`manage_clamd` says to include that class for you.
So if you also declare the clamd class, you will get an error.  Puppet only allows a class to be declared once.

**Comment by wojciej** [comment]
Here are the configs:

``` ruby
# init.pp
# Main class of clamav
# Declare main config here
#
# http://www.clamav.net
# http://www.clamxav.com
#

class clamav (
  $manage_user       = $clamav::params::manage_user,
  $manage_repo       = $clamav::params::manage_repo,
  $manage_clamd      = $clamav::params::manage_clamd,
  $manage_freshclam  = $clamav::params::manage_freshclam,
  $clamav_package    = $clamav::params::clamav_package,

  $user              = $clamav::params::user,
  $comment           = $clamav::params::comment,
  $uid               = $clamav::params::uid,
  $gid               = $clamav::params::gid,
  $home              = $clamav::params::home,
  $shell             = $clamav::params::shell,
  $group             = $clamav::params::group,
  $groups            = $clamav::params::groups,

  $clamd_package     = $clamav::params::clamd_package,
  $clamd_config      = $clamav::params::clamd_config,
  $clamd_service     = $clamav::params::clamd_service,
  $clamd_options     = $clamav::params::clamd_options,

  #$daily_scan_path  = $clamav::params::daily_scan_path,
  #$hourly_scan_path  = $clamav::params::hourly_scan_path,

  $freshclam_package = $clamav::params::freshclam_package,
  $freshclam_config  = $clamav::params::freshclam_config,
  $freshclam_service = $clamav::params::freshclam_service,
  $freshclam_options = $clamav::params::freshclam_options,
) inherits clamav::params {

  validate_bool($manage_user)
  validate_bool($manage_repo)
  validate_bool($manage_clamd)
  validate_bool($manage_freshclam)
  validate_string($clamav_package)

  if $manage_repo { require epel }

  if $manage_user {
    class { 'clamav::user':
      user    => $user,
      comment => $comment,
      uid     => $uid,
      gid     => $gid,
      home    => $home,
      shell   => $shell,
      group   => $group,
      groups  => $groups,
      before  => Package['clamav'],
      require => Anchor['clamav::begin'],
    }
  }


  package { 'clamav':
    ensure  => installed,
    name    => $clamav_package,
    require => Anchor['clamav::begin'],
  }

  if $manage_clamd {
    class { 'clamav::clamd':
      clamd_package => $clamd_package,
      clamd_config  => $clamd_config,
      clamd_service => $clamd_service,
      clamd_options => $clamd_options,
      require       => Package['clamav'],
      before        => Anchor['clamav::end'],
    }
  }

  if $manage_freshclam {
    class { 'clamav::freshclam':
      freshclam_package => $freshclam_package,
      freshclam_config  => $freshclam_config,
      freshclam_service => $freshclam_service,
      freshclam_options => $freshclam_options,
      require           => Package['clamav'],
      before            => Anchor['clamav::end'],
    }
  }

  # Anchor this as per #8040 - this ensures that classes won't float off and
  # mess everything up.  You can read about this at:
  # http://docs.puppetlabs.com/puppet/2.7/reference/lang_containment.html#known-issues
  anchor { 'clamav::begin': }
  anchor { 'clamav::end': }

}
```

Clamd class

``` ruby
# clamd.pp
# Set up clamd config and service.
#

class clamav::clamd (
  $clamd_package = $clamav::params::clamd_package,
  $clamd_config  = $clamav::params::clamd_config,
  $daily_scan_path  = $clamav::params::daily_scan_path,
  $hourly_scan_path  = $clamav::params::hourly_scan_path,
  $clamd_service = $clamav::params::clamd_service,
  $clamd_options = $clamav::params::clamd_options,
  $user = $clamav::params::user,
) inherits clamav::params {

  validate_string($clamd_package)
  validate_absolute_path($clamd_config)
  validate_string($clamd_service)
  validate_hash($clamd_options)

  $config_options = merge($clamav::params::clamd_default_options, $clamd_options)

  package { 'clamd':
    ensure => installed,
    name   => $clamd_package,
    before => File['clamd.conf'],
  }

  file { 'clamd.conf':
    ensure  => file,
    path    => $clamd_config,
    mode    => '0644',
    owner   => 'root',
    group   => 'root',
    content => template("${module_name}/clamd.conf.${::osfamily}.erb"),
  }

  service { 'clamd':
    ensure     => running,
    name       => $clamd_service,
    enable     => true,
    hasrestart => true,
    hasstatus  => true,
    subscribe  => File['clamd.conf'],
  }

}
```

**Comment by edestecd** [comment]
This code is copied from the clamav module.  Are you trying to change that?

To use the module you would install the module with the `puppet module` subcommand
and then use its classes, rather than modifying the code in a module.

Are you using nodes or a sites.pp or Enterprise?  How do you normally include your classes?
This was the code I was hoping to see.

Are you trying to add new features?  If so I'd be glad to help.  It would be easiest if you fork this repository, so I can see the changes.

**Comment by edestecd** [comment]
You can see how to use the module here:
[README.md](https://github.com/edestecd/puppet-clamav/blob/master/README.md#usage)

Do you have code like that somewhere?

**Comment by wojciej** [comment]
Hi,
So here is the thing. I have Foreman installed on master host, I have additional host connected to it as a client.
In foreman I have imported main class clamav and subclasses:
clamav::clamd
clamav::freshclam
clamav::params
clamav::user

Then I attach those classes to my host client in Foreman. Next - to fasten the process - I connect to client via ssh and run puppet agent -t with debug mode on.
And here is where I get those errors.

I am not creating any code on my side except adding to freshclam classes additional templates for daily and hourly scan scripts.

I guess I am using this different way that it was designed ?

**Comment by edestecd** [comment]
OK, now I can see why you are having both of your issues.
- `Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration:`
  This error is caused by including both the main clamav class and those subclasses.
  The main clamav class already includes the subclasses for you.  Have a look here: [clamav](https://github.com/edestecd/puppet-clamav/blob/master/manifests/init.pp)  
  So, you can't do both.  
  Either:  
  only include the main clamav class (preferred)  
  OR  
  only include the subclasses
- `Error: /Stage[main]/Clamav::User/User[clamav]/uid: change from 114 to 496 failed: Could not set uid on user[clamav]:`  This error is caused by including the subclasses, instead of using the main clamav class.  The main clamav class makes the other classes require the clamav::user class to solve this problem for you.  That is why it is preferred to just use the main class only.  As far as I know, there is no way in Foreman to add require or before dependencies on a class.

I recommend you remove the subclasses and pass all your params through the main clamav class.
You can override/set the params in Foreman by going here:
Configure -> Puppet classes -> search clamav -> Smart Class Parameter Tab
Change these here to include the classes...  
manage clamd
manage freshclam
manage user

![screen shot 2015-04-01 at 8 13 42 am](https://cloud.githubusercontent.com/assets/107281/6940676/2ad4a9f6-d847-11e4-914f-8ff47dc56d63.png)

**Comment by edestecd** [comment]
@wojciej1, did this solve your issues?

**Comment by wojciej** [comment]
Hello,
Sorry for such a late response, I was on Easter Holidays..
Anyway, yes your instructions help me to solve the issue.

Thanks a lot for your help and for the good work you did here.
Take care.
Jarek
